CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR NOT NULL,
	email VARCHAR NOT NULL UNIQUE,
	CONSTRAINT name_not_blank CHECK (TRIM(name) <> ''),
	CONSTRAINT email_not_blank CHECK (TRIM(email) <> ''),
	CONSTRAINT email_no_whitespace CHECK (email NOT LIKE '% %')
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    is_available BOOL NOT NULL,
    request_id INTEGER,
    CONSTRAINT name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT description_not_blank CHECK (TRIM(description) <> '')
);