CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR NOT NULL,
	email VARCHAR NOT NULL UNIQUE,
	CONSTRAINT user_name_not_blank CHECK (TRIM(name) <> ''),
	CONSTRAINT email_not_blank CHECK (TRIM(email) <> ''),
	CONSTRAINT email_no_whitespace CHECK (email NOT LIKE '% %')
);

CREATE TABLE IF NOT EXISTS requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar NOT NULL,
    requestor_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    date_created TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    is_available BOOL NOT NULL,
    request_id INTEGER REFERENCES requests(id) ON DELETE SET NULL,
    CONSTRAINT item_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT description_not_blank CHECK (TRIM(description) <> '')
);

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
    booker_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    status VARCHAR(8) NOT NULL,
    CONSTRAINT end_date_is_after_start_date CHECK (end_date > start_date)
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar NOT NULL,
    item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
    author_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    date_created TIMESTAMP NOT NULL
);